// GENERATED by npm run sync-studio from the threads-carousel fork. Do not edit here.
// @ts-nocheck
// ============================================================
// Applies an animation frame to a rendered slide.
//
// Writes inline styles straight onto the DOM rather than going through React
// state. A 75-frame export would otherwise trigger 75 reconciliation passes
// and font reflows per slide, which is both slow and visibly unstable.
// ============================================================

import { layerStateAt, backgroundStateAt } from "./animation";
import type { MotionPreset } from "./types";

/** Length of the ambient background loops, in seconds. Matches globals.css. */
const AMBIENT_LOOP_SEC = 8;

/** Elements the animator touches, in stagger order. Background is separate. */
const LAYER_SELECTOR = '[data-anim]:not([data-anim="bg"])';
const BG_SELECTOR = '[data-anim="bg"]';

/**
 * Set every animatable element inside `container` to its state at progress `t`.
 * Stagger index is document order, so slides animate top to bottom without any
 * per-slide configuration.
 */
export function applyFrame(
  container: HTMLElement,
  t: number,
  preset: MotionPreset
): void {
  const layers = container.querySelectorAll<HTMLElement>(LAYER_SELECTOR);

  layers.forEach((el, i) => {
    const s = layerStateAt(t, i, preset, layers.length);
    // A layer with a static base transform (e.g. a Maximalist panel's fixed
    // rotate) carries it in data-anim-base rather than el.style.transform, so
    // the animated transform composes with it instead of overwriting it.
    // Order matters: base is applied first (rightmost), so the layer rotates
    // about its own center, then scales, then the whole result is carried
    // across the screen by the translate — a straight slide-in, not an arc.
    const base = el.getAttribute("data-anim-base") || "";
    el.style.opacity = String(s.opacity);
    el.style.transform =
      `translateX(${s.translateX.toFixed(2)}px) translateY(${s.translateY.toFixed(2)}px) scale(${s.scale.toFixed(4)}) ${base}`.trim();
    // Transforms on inline elements are ignored; promote without changing layout.
    if (!el.style.display) el.style.display = "block";
    el.style.willChange = "opacity, transform";
  });

  // Ambient CSS loops (the Aurora orbs, particles and breathing dot) run on
  // their own infinite timelines. Pause them and seek with a negative delay so
  // a frame captures an exact moment instead of whatever real time it is. The
  // loops are 8s; the slide timeline is normalised, so map t onto one cycle.
  container.style.setProperty("--sa-play", "paused");
  container.style.setProperty("--sa-t", `${(t * AMBIENT_LOOP_SEC).toFixed(3)}s`);

  const bg = container.querySelector<HTMLElement>(BG_SELECTOR);
  if (bg) {
    const b = backgroundStateAt(t, preset);
    bg.style.transformOrigin = "center center";
    bg.style.transform = `translate(${b.driftX.toFixed(2)}px, ${b.driftY.toFixed(2)}px) scale(${b.scale.toFixed(4)})`;
    bg.style.willChange = "transform";
  }
}

/**
 * Remove everything applyFrame set, returning the node to its static state.
 * Called before PNG and PDF export so those paths are unaffected.
 */
export function resetFrame(container: HTMLElement): void {
  container.style.removeProperty("--sa-play");
  container.style.removeProperty("--sa-t");
  const all = container.querySelectorAll<HTMLElement>("[data-anim]");
  all.forEach((el) => {
    el.style.opacity = "";
    // Restore the static base (e.g. a panel's fixed rotate) rather than
    // clearing to nothing — an empty transform would strip a look's own
    // tilt from an offscreen node until some unrelated re-render restores it.
    const base = el.getAttribute("data-anim-base");
    el.style.transform = base || "";
    el.style.transformOrigin = "";
    el.style.willChange = "";
    if (el.style.display === "block") el.style.display = "";
  });
}

/**
 * Wait for the next paint, with a timeout fallback.
 *
 * requestAnimationFrame does not fire in a background tab. An export takes
 * minutes, and switching tabs mid-export is the normal thing to do, so waiting
 * on rAF alone would stall the run indefinitely. The race keeps it moving.
 */
export function nextFrame(): Promise<void> {
  return new Promise<void>((resolve) => {
    let done = false;
    const finish = () => {
      if (done) return;
      done = true;
      resolve();
    };
    requestAnimationFrame(() => finish());
    setTimeout(finish, 32);
  });
}
