// GENERATED by npm run sync-studio from the threads-carousel fork. Do not edit here.
// @ts-nocheck
// ============================================================
// Animation timeline math.
//
// Pure functions — no DOM, no React, no browser APIs. Given a normalised
// progress value t in [0,1], returns what each layer should look like at that
// instant. anim-dom.ts turns these into inline styles; nothing else here knows
// about elements.
// ============================================================

import type { MotionId, MotionPreset } from "./types";

// ---- Easing ----

/** Decelerating ease. Fast out of the gate, settles softly. */
export function easeOutCubic(x: number): number {
  return 1 - Math.pow(1 - x, 3);
}

/** Gentle both ends — used for background motion, which should never snap. */
export function easeInOutSine(x: number): number {
  return -(Math.cos(Math.PI * x) - 1) / 2;
}

/**
 * Decelerating ease that overshoots past 1 before settling — a layer lands
 * past its resting position and springs back, instead of just arriving.
 * `overshoot` is the standard back-ease constant; higher springs further.
 */
export function easeOutBack(x: number, overshoot: number): number {
  const c1 = overshoot;
  const c3 = c1 + 1;
  const p = x - 1;
  return 1 + c3 * p * p * p + c1 * p * p;
}

const clamp01 = (v: number) => (v < 0 ? 0 : v > 1 ? 1 : v);

// ---- Presets ----
//
// Bands are fractions of t, not seconds, so changing the duration stretches
// the whole timeline proportionally rather than leaving a fixed-length
// entrance inside a longer slide.

export const MOTION_PRESETS: Record<MotionId, MotionPreset> = {
  // Fade and rise only. No scale on text. The quiet default.
  editorial: {
    id: "editorial",
    name: "Editorial",
    entranceEnd: 0.48,
    stagger: 0.11,
    layerDuration: 0.3,
    riseFrom: 24,
    scaleFrom: 1,
    bgScaleFrom: 1,
    bgScaleTo: 1.04,
    bgDriftPx: 0,
  },
  // Bigger offsets and a slight scale-in. For hooks that need more punch.
  kinetic: {
    id: "kinetic",
    name: "Kinetic",
    entranceEnd: 0.56,
    stagger: 0.14,
    layerDuration: 0.32,
    riseFrom: 46,
    scaleFrom: 0.94,
    bgScaleFrom: 1,
    bgScaleTo: 1.08,
    bgDriftPx: 0,
  },
  // Text barely moves; the background carries it.
  drift: {
    id: "drift",
    name: "Drift",
    entranceEnd: 0.42,
    stagger: 0.1,
    layerDuration: 0.36,
    riseFrom: 0,
    scaleFrom: 1,
    bgScaleFrom: 1.02,
    bgScaleTo: 1.1,
    bgDriftPx: 46,
  },
  // A filled panel (Maximalist, Caption) and its text arrive as one object:
  // horizontal travel with a back-ease landing, opacity saturating well
  // before the travel settles so the panel is never half-see-through on top
  // of its own background. See specs/look-parity-build.md, Task 1.
  stamp: {
    id: "stamp",
    name: "Stamp",
    entranceEnd: 0.4,
    stagger: 0.16,
    layerDuration: 0.34,
    riseFrom: 0,
    scaleFrom: 0.92,
    bgScaleFrom: 1,
    bgScaleTo: 1,
    bgDriftPx: 0,
    travelXFrom: 480,
    opacityBoost: 2.4,
    overshoot: 1.15,
  },
};

// ---- State at a point in time ----

export interface LayerState {
  opacity: number;
  translateX: number;
  translateY: number;
  scale: number;
}

export interface BackgroundState {
  scale: number;
  driftX: number;
  driftY: number;
}

/**
 * Where text layer `staggerIndex` sits at progress `t`.
 * Layer 0 starts immediately; each subsequent layer is offset by `stagger`.
 */
export function layerStateAt(
  t: number,
  staggerIndex: number,
  preset: MotionPreset,
  layerCount = 1
): LayerState {
  // Spread the layers so the last one finishes exactly at entranceEnd. Using a
  // fixed per-layer offset instead would make a 3-layer slide finish in a third
  // of the time of a 9-layer one, and the deck would read as inconsistent.
  const span = Math.max(0, preset.entranceEnd - preset.layerDuration);
  const stagger = layerCount > 1 ? Math.min(preset.stagger, span / (layerCount - 1)) : 0;

  const start = staggerIndex * stagger;
  const local = clamp01((t - start) / preset.layerDuration);

  // Overshoot presets (stamp) use a back-ease for the transform so a layer
  // lands past rest and springs back; the three original presets have no
  // overshoot and fall back to the exact easeOutCubic curve they always used.
  const overshoot = preset.overshoot ?? 0;
  const landEase = overshoot > 0 ? easeOutBack(local, overshoot) : easeOutCubic(local);

  // Opacity can saturate faster than the transform settles — a filled panel
  // half-see-through on top of its own background reads as broken, not
  // mid-entrance. opacityBoost defaults to 1, which ties opacity to the same
  // curve as translateY/scale, exactly matching pre-stamp behavior.
  const opacityBoost = preset.opacityBoost ?? 1;
  const opacity = clamp01(easeOutCubic(Math.min(1, local * opacityBoost)));

  // Travel direction alternates by layer so a deck with multiple panelled
  // layers (list/stat items, once panels are used there) doesn't stamp every
  // layer in from the same side. A single-panel slide just gets one direction.
  const dirSign = staggerIndex % 2 === 0 ? 1 : -1;

  return {
    opacity,
    translateX: dirSign * (preset.travelXFrom ?? 0) * (1 - landEase),
    translateY: preset.riseFrom * (1 - landEase),
    scale: preset.scaleFrom + (1 - preset.scaleFrom) * landEase,
  };
}

/**
 * Background motion runs across the whole timeline, independent of the text
 * entrance — that separation is what keeps a slide from reading as a build.
 */
export function backgroundStateAt(t: number, preset: MotionPreset): BackgroundState {
  const eased = easeInOutSine(clamp01(t));
  return {
    scale: preset.bgScaleFrom + (preset.bgScaleTo - preset.bgScaleFrom) * eased,
    driftX: -preset.bgDriftPx * eased,
    driftY: preset.bgDriftPx * 0.4 * eased,
  };
}

/** Frame count for a duration at a fixed frame rate. */
export function frameCount(durationSec: number, fps: number): number {
  return Math.max(2, Math.round(durationSec * fps));
}
