// GENERATED by npm run sync-studio from the threads-carousel fork. Do not edit here.
// @ts-nocheck
import type { DecorTable, ResolvedDecor, SlideDecorOverride } from "./types";

/**
 * Caption's furniture: a section label chip and one corner glyph per slide.
 * Positions are percentages of canvas width/height, chosen to stay clear of
 * the copy column, which runs from 8.5% to 91.5%.
 */
export const CAPTION_DECOR: DecorTable = [
  { label: "COVER", stickers: [{ glyph: "✦", x: 88, y: 16, size: 2.4 }] },
  { label: "STATEMENT", stickers: [{ glyph: "✺", x: 12, y: 82, size: 2.2 }] },
  { label: "HOW IT WORKS", stickers: [{ glyph: "✦", x: 86, y: 78, size: 2.0 }] },
  { label: "THE LIST", stickers: [{ glyph: "▲", x: 90, y: 20, size: 1.9 }] },
  { label: "CHECKLIST", stickers: [{ glyph: "●", x: 10, y: 20, size: 1.8 }] },
  { label: "PROCESS", stickers: [{ glyph: "✦", x: 89, y: 84, size: 2.1 }] },
  { label: "REAL TALK", stickers: [{ glyph: "✺", x: 11, y: 18, size: 2.3 }] },
  { label: "PRO TIP", stickers: [{ glyph: "★", x: 87, y: 82, size: 2.5 }] },
];

/** Maximalist runs hotter: two glyphs per slide, larger, rotated. */
export const MAXIMALIST_DECOR: DecorTable = [
  { label: "COVER", stickers: [{ glyph: "★", x: 88, y: 14, size: 3.4, rotate: -12 }, { glyph: "✦", x: 12, y: 86, size: 2.6, rotate: 8 }] },
  { label: "STATEMENT", stickers: [{ glyph: "✺", x: 11, y: 16, size: 3.0, rotate: 10 }, { glyph: "●", x: 89, y: 84, size: 2.2 }] },
  { label: "HOW IT WORKS", stickers: [{ glyph: "▲", x: 90, y: 80, size: 2.8, rotate: -6 }, { glyph: "★", x: 10, y: 22, size: 2.4, rotate: 14 }] },
  { label: "THE LIST", stickers: [{ glyph: "✦", x: 87, y: 18, size: 2.6, rotate: -10 }] },
  { label: "CHECKLIST", stickers: [{ glyph: "●", x: 12, y: 80, size: 2.4 }] },
  { label: "PROCESS", stickers: [{ glyph: "✺", x: 88, y: 82, size: 3.0, rotate: 12 }] },
  { label: "REAL TALK", stickers: [{ glyph: "★", x: 10, y: 18, size: 3.2, rotate: -14 }, { glyph: "▲", x: 90, y: 86, size: 2.3, rotate: 6 }] },
  { label: "PRO TIP", stickers: [{ glyph: "✦", x: 86, y: 20, size: 2.8, rotate: 9 }] },
];

/**
 * Furniture for one slide. The table repeats once exhausted, so a deck longer
 * than the table still gets decoration. Per-slide overrides win.
 */
export function resolveDecor(
  table: DecorTable,
  index: number,
  overrides?: SlideDecorOverride,
): ResolvedDecor {
  const base = table[index % table.length];
  return {
    label: overrides?.label ?? base.label,
    stickers: overrides?.stickers ?? base.stickers,
  };
}
