// GENERATED by npm run sync-studio from the threads-carousel fork. Do not edit here.
// @ts-nocheck
// ============================================================
// Style axes and format presets.
//
// Three independent axes compose a StylePreset at runtime:
//   FONT_STYLES   — typeface / font family
//   COLOR_THEMES  — background, text, and accent colors
//   composePreset — merges font + color + purpose into StylePreset
//
// FORMAT_PRESETS — canvas dimensions per platform (unchanged)
// ============================================================

import type {
  StylePreset,
  FormatPreset,
  FormatId,
  FontId,
  FontStyle,
  SurfaceId,
  Surface,
  AccentId,
  Accent,
  PurposeId,
  Look,
  LookId,
  CqwScale,
  BgType,
  MotionId,
} from "./types";
import { CAPTION_DECOR, MAXIMALIST_DECOR } from "./looks-decor";

// ---- Font styles ----

export const FONT_STYLES: Record<FontId, FontStyle> = {
  // Geometric display — bold, rounded, distinctive. Unbounded everywhere.
  minimal: {
    id: "minimal",
    name: "Minimal",
    fontFamily: "var(--font-unbounded)",
    hookFontFamily: "var(--font-unbounded)",
  },
  // Classic serif — Playfair for both headings and body.
  editorial: {
    id: "editorial",
    name: "Editorial",
    fontFamily: "var(--font-playfair)",
    hookFontFamily: "var(--font-playfair)",
  },
  // Neutral sans-serif — pure Inter throughout. The most "standard" look.
  clean: {
    id: "clean",
    name: "Clean",
    fontFamily: "var(--font-inter)",
    hookFontFamily: "var(--font-inter)",
  },
  // Monospace technical — JetBrains Mono. Tech/dev feel.
  mono: {
    id: "mono",
    name: "Mono",
    fontFamily: "var(--font-jetbrains-mono)",
    hookFontFamily: "var(--font-jetbrains-mono)",
  },
  // Narrow tall condensed — Oswald. Editorial-poster feel.
  condensed: {
    id: "condensed",
    name: "Condensed",
    fontFamily: "var(--font-oswald)",
    hookFontFamily: "var(--font-oswald)",
  },
};

// ---- Color themes ----

// ---- Surfaces: bg + text neutrals (no pop color) ----
export const SURFACES: Record<SurfaceId, Surface> = {
  dark: {
    id: "dark",
    name: "Dark",
    bg: "#0A0A0A",
    textColor: "#FFFFFF",
    textSecondary: "rgba(255,255,255,0.5)",
    accentColor: "#FFFFFF",
  },
  white: {
    id: "white",
    name: "White",
    bg: "#FFFFFF",
    textColor: "#0B0B0B",
    textSecondary: "rgba(0,0,0,0.4)",
    accentColor: "#0B0B0B",
  },
  // Cool zinc grey — neutral, editorial, Vercel-like. Distinctly cool.
  light: {
    id: "light",
    name: "Light",
    bg: "#F4F4F5",
    textColor: "#18181B",
    textSecondary: "rgba(24,24,27,0.5)",
    accentColor: "#18181B",
  },
  // Notebook cream — pushed further into yellow. Distinctly warm.
  paper: {
    id: "paper",
    name: "Paper",
    bg: "#ECE2C8",
    textColor: "#3A2F1C",
    textSecondary: "rgba(58,47,28,0.55)",
    accentColor: "#78350F",
  },
  gradient: {
    id: "gradient",
    name: "Gradient",
    bg: "#1a1a2e",
    bgGradient:
      "linear-gradient(135deg, #6366F1 0%, #EC4899 50%, #F59E0B 100%)",
    textColor: "#FFFFFF",
    textSecondary: "rgba(255,255,255,0.7)",
    accentColor: "#FFFFFF",
  },
  pastel: {
    id: "pastel",
    name: "Pastel",
    bg: "#EDE9FE",
    textColor: "#1E1B4B",
    textSecondary: "rgba(30,27,75,0.45)",
    accentColor: "#6D28D9",
  },
  neon: {
    id: "neon",
    name: "Neon",
    bg: "#0F172A",
    bgGradient: "linear-gradient(160deg, #0F172A 0%, #1E1B4B 100%)",
    textColor: "#E0F2FE",
    textSecondary: "rgba(224,242,254,0.4)",
    accentColor: "#06B6D4",
  },
  // Black→red radial — dramatic dark surface (inspired by ref 7).
  ember: {
    id: "ember",
    name: "Ember",
    bg: "#0A0A0A",
    bgGradient: "radial-gradient(circle at 30% 20%, #8B0000 0%, #1A0606 45%, #0A0A0A 100%)",
    textColor: "#F5F5F4",
    textSecondary: "rgba(245,245,244,0.55)",
    accentColor: "#F5F5F4",
  },
};

// ---- Accents: the pop color used for highlighted words ----
export const ACCENTS: Record<AccentId, Accent> = {
  yellow:  { id: "yellow",  name: "Yellow",  color: "#FACC15" },
  red:     { id: "red",     name: "Red",     color: "#DC2626" },
  teal:    { id: "teal",    name: "Teal",    color: "#14B8A6" },
  // Pink-family coral (Pantone Living Coral 2019 inspired) — NOT orange-leaning.
  coral:   { id: "coral",   name: "Coral",   color: "#FB7185" },
  // Bright pumpkin orange — clearly distinct from coral.
  orange:  { id: "orange",  name: "Orange",  color: "#F97316" },
  violet:  { id: "violet",  name: "Violet",  color: "#A78BFA" },
  lime:    { id: "lime",    name: "Lime",    color: "#D9F056" },
  // Classic brand blue — high contrast, fills the biggest palette gap.
  blue:    { id: "blue",    name: "Blue",    color: "#3B82F6" },
  // Magenta/fuchsia — pairs beautifully with pastel lilac surface.
  fuchsia: { id: "fuchsia", name: "Fuchsia", color: "#C026D3" },
  // Hot pink — central stop of the gradient surface, pairs well with it.
  pink:    { id: "pink",    name: "Pink",    color: "#EC4899" },
  // Golden amber — final stop of the gradient; pops against its purple/pink sections.
  amber:   { id: "amber",   name: "Amber",   color: "#F59E0B" },
};

// ---- Compose a StylePreset from the four axes ----

// ---- Curated looks ----
//
// A look is a checked combination of the three axes plus the typography the
// axes cannot express on their own. Adding a look is additive: define pins and
// overrides here, add its id to LookId, and it appears in the toolbar.

/**
 * The reference type scale, transcribed from supaslides.app. Sizes are a
 * percentage of canvas width. Shared by every look in that family; individual
 * looks override only `cover` and `coverLh`.
 */
export const REFERENCE_SCALE: CqwScale = {
  cover: 12.5,
  coverLh: 0.96,
  stmt: 8.6,
  statNum: 40,
  statLabel: 5.6,
  statSupport: 2.45,
  listTitle: 5.6,
  listText: 3.6,
  stepLabel: 2.1,
  stepTitle: 6.6,
  stepBody: 2.6,
  cta: 8.2,
  ctaHandle: 2.3,
  sub: 2.5,
  foot: 1.85,
};

export const LOOKS: Record<LookId, Look> = {
  none: {
    id: "none",
    name: "None",
    pins: {},
    overrides: {},
  },

  // Soft Organic — quiet, warm, lowercase. The headline itself carries the
  // accent colour rather than one highlighted word inside it, roman and italic
  // mix within the sentence, and a diffuse bloom replaces hard-edged shapes.
  "soft-organic": {
    id: "soft-organic",
    name: "Soft Organic",
    pins: {
      font: "editorial",
      bg: "bloom",
    },
    overrides: {
      // Warm near-black rather than neutral — the whole look leans warm.
      bg: "#0C0709",
      bgGradient: undefined,
      textColor: "#F5EDEF",
      textSecondary: "rgba(245,237,239,0.55)",
      // Display serif at a normal weight. Playfair at 800 is too heavy to read
      // as calm; the softness comes from the lighter weight and open leading.
      hookFontWeight: 500,
      hookLineHeight: 1.12,
      hookLetterSpacing: "-0.005em",
      // Sentence case. The reference look ran everything lowercase, but the
      // copy reads better with normal capitalisation at this size.
      hookTransform: "none",
      // Body headline keeps the serif, just lighter and tighter than default.
      bodyFontWeight: 500,
      bodyLineHeight: 1.16,
      // The paragraph under it drops to the neutral sans, so the serif stays
      // the voice and the supporting copy reads as quiet.
      subFontFamily: "var(--font-inter)",
      subFontWeight: 400,
      subLineHeight: 1.45,
      subTextMaxSize: 44,
      titleUppercase: false,
      titleDivider: false,
      // Task 6 furniture: soft translucent pill rows with a coral dot, and a
      // tiny lowercase corner label instead of the uppercase bordered badge.
      // Values (radius, row opacity, dot size) pulled from the live
      // reference's own "Soft Organic" style. See specs/look-parity-build.md.
      listRowStyle: "pill",
      listNumStyle: "dot",
      badgeStyle: "tiny-lowercase",
    },
  },

  // Aurora — rebuilt against the live supaslides.app reference rather than a
  // description of it. The whole family shares one typographic core: Manrope
  // 800, lowercase, -0.02em, line-height ~0.98, sized as a fraction of canvas
  // width. Emphasis is tonal — a phrase is brighter than its surroundings —
  // not a pop colour. The accent survives only as light (drifting orbs,
  // particles) and as the dot that closes the headline.
  aurora: {
    id: "aurora",
    name: "Aurora",
    pins: {
      surface: "dark",
      bg: "aurora",
    },
    overrides: {
      bg: "#07050A",
      bgGradient: undefined,
      textColor: "#F0EBF4",
      fontFamily: "var(--font-manrope)",
      hookFontFamily: "var(--font-manrope)",
      bodyFontFamily: "var(--font-manrope)",
      subFontFamily: "var(--font-manrope)",
      hookFontWeight: 800,
      hookLineHeight: 0.96,
      hookLetterSpacing: "-0.02em",
      hookTransform: "lowercase",
      hookSizeCqw: 12.5,
      hookMaxWidthPct: 92,
      bodyFontWeight: 800,
      bodyLineHeight: 0.98,
      subFontWeight: 500,
      subLineHeight: 1.45,
      subSizeCqw: 2.5,
      subMaxWidthPct: 62,
      cqwScale: REFERENCE_SCALE,
      subTransform: "lowercase",
      emphasis: "tonal",
      footStyle: "mono",
      accentDot: true,
      titleUppercase: false,
      // Lowercase travels with the rest of the core: this look already
      // runs hook and sub lowercase, so a sentence-case title breaks it.
      titleTransform: "lowercase",
      titleDivider: false,
    },
  },

  // Stealth — the same tonal core as Aurora over two large centred blooms.
  // Quieter and more symmetrical; the light sits behind the type rather than
  // drifting past it.
  stealth: {
    id: "stealth",
    name: "Stealth",
    pins: { surface: "dark", bg: "stealthbloom" },
    overrides: {
      bg: "#08070B",
      bgGradient: undefined,
      textColor: "#EDEAF2",
      fontFamily: "var(--font-manrope)",
      hookFontFamily: "var(--font-manrope)",
      bodyFontFamily: "var(--font-manrope)",
      subFontFamily: "var(--font-manrope)",
      hookFontWeight: 800,
      hookLineHeight: 0.96,
      hookLetterSpacing: "-0.02em",
      hookTransform: "lowercase",
      hookSizeCqw: 12.5,
      hookMaxWidthPct: 92,
      bodyFontWeight: 800,
      bodyLineHeight: 0.98,
      subFontWeight: 500,
      subLineHeight: 1.45,
      subSizeCqw: 2.5,
      subMaxWidthPct: 62,
      subTransform: "lowercase",
      cqwScale: REFERENCE_SCALE,
      emphasis: "tonal",
      footStyle: "mono",
      accentDot: true,
      titleUppercase: false,
      // Lowercase travels with the rest of the core: this look already
      // runs hook and sub lowercase, so a sentence-case title breaks it.
      titleTransform: "lowercase",
      titleDivider: false,
    },
  },

  // Swiss — the one break from the family. Body-face type rather than the
  // display grotesk, uppercase labels on very wide tracking, a hairline rule
  // with a dot, and the accent carried by a script face.
  swiss: {
    id: "swiss",
    name: "Swiss",
    pins: { surface: "dark", bg: "swissrule" },
    overrides: {
      bg: "#0B0A0C",
      bgGradient: undefined,
      textColor: "#F2F0F3",
      fontFamily: "var(--font-inter)",
      hookFontFamily: "var(--font-inter)",
      bodyFontFamily: "var(--font-inter)",
      subFontFamily: "var(--font-inter)",
      hookFontWeight: 600,
      hookLineHeight: 1.02,
      hookLetterSpacing: "0em",
      hookTransform: "none",
      hookSizeCqw: 13.5,
      bodyFontWeight: 600,
      bodyLineHeight: 1.02,
      subFontWeight: 400,
      subLineHeight: 1.8,
      subSizeCqw: 2.2,
      subMaxWidthPct: 66,
      subTransform: "uppercase",
      cqwScale: { ...REFERENCE_SCALE, cover: 13.5, coverLh: 1 },
      emphasis: "script",
      footStyle: "mono",
      titleUppercase: true,
      titleDivider: false,
    },
  },

  // Vista — light rising from below the frame. Not a sunburst: one very large
  // soft glow low in the canvas, a single arc outline, film grain and a soft
  // vignette. Emphasis returns to the accent colour.
  vista: {
    id: "vista",
    name: "Vista",
    pins: { surface: "dark", bg: "sunglow" },
    overrides: {
      bg: "#0C0910",
      bgGradient: undefined,
      textColor: "#F4F1F6",
      fontFamily: "var(--font-manrope)",
      hookFontFamily: "var(--font-manrope)",
      bodyFontFamily: "var(--font-manrope)",
      subFontFamily: "var(--font-manrope)",
      hookFontWeight: 800,
      hookLineHeight: 0.9,
      hookLetterSpacing: "-0.02em",
      hookTransform: "lowercase",
      hookSizeCqw: 13.5,
      hookMaxWidthPct: 92,
      bodyFontWeight: 800,
      bodyLineHeight: 0.98,
      subFontWeight: 500,
      subLineHeight: 1.45,
      subSizeCqw: 2.5,
      subMaxWidthPct: 62,
      subTransform: "lowercase",
      cqwScale: { ...REFERENCE_SCALE, cover: 13.5, coverLh: 0.9 },
      emphasis: "accent",
      footStyle: "mono",
      titleUppercase: false,
      // Lowercase travels with the rest of the core: this look already
      // runs hook and sub lowercase, so a sentence-case title breaks it.
      titleTransform: "lowercase",
      titleDivider: false,
      // Task 6 furniture, added on top of the existing look above without
      // touching its type/colour system: a thin frame, a header triad, a
      // rising ray burst, and circled list numerals. Values pulled from the
      // live reference. See specs/look-parity-build.md, Task 6.
      cardFrame: true,
      headerTriad: true,
      headerBrand: "Est. Vista",
      radialRays: true,
      listNumStyle: "vista",
    },
  },

  // Editorial — the quietest. No wash at all; structure comes from hairline
  // rules, and the accent appears only as an italic phrase.
  "editorial-look": {
    id: "editorial-look",
    name: "Editorial",
    pins: { surface: "dark", bg: "none" },
    overrides: {
      bg: "#0A0A0B",
      bgGradient: undefined,
      textColor: "#F1EFF1",
      fontFamily: "var(--font-manrope)",
      hookFontFamily: "var(--font-manrope)",
      bodyFontFamily: "var(--font-manrope)",
      subFontFamily: "var(--font-manrope)",
      hookFontWeight: 600,
      hookLineHeight: 0.98,
      hookLetterSpacing: "-0.02em",
      hookTransform: "lowercase",
      hookSizeCqw: 11.5,
      hookMaxWidthPct: 92,
      bodyFontWeight: 600,
      bodyLineHeight: 0.98,
      subFontWeight: 500,
      subLineHeight: 1.5,
      subSizeCqw: 2.5,
      subMaxWidthPct: 62,
      subTransform: "lowercase",
      cqwScale: { ...REFERENCE_SCALE, cover: 11.5, coverLh: 0.98 },
      emphasis: "accent-italic",
      footStyle: "mono",
      titleUppercase: false,
      // Lowercase travels with the rest of the core: this look already
      // runs hook and sub lowercase, so a sentence-case title breaks it.
      titleTransform: "lowercase",
      titleDivider: false,
    },
  },

  // Organic — a soft-light bloom and film grain over a warm dark ground. The
  // accent phrase is italic and carries an underline swash.
  organic: {
    id: "organic",
    name: "Organic",
    pins: { surface: "dark", bg: "organicbloom" },
    overrides: {
      bg: "#0C0809",
      bgGradient: undefined,
      textColor: "#F3EDEA",
      fontFamily: "var(--font-manrope)",
      hookFontFamily: "var(--font-manrope)",
      bodyFontFamily: "var(--font-manrope)",
      subFontFamily: "var(--font-manrope)",
      hookFontWeight: 800,
      hookLineHeight: 0.98,
      hookLetterSpacing: "-0.02em",
      hookTransform: "lowercase",
      hookSizeCqw: 11,
      hookMaxWidthPct: 92,
      bodyFontWeight: 800,
      bodyLineHeight: 0.98,
      subFontWeight: 500,
      subLineHeight: 1.5,
      subSizeCqw: 2.5,
      subMaxWidthPct: 62,
      subTransform: "lowercase",
      cqwScale: { ...REFERENCE_SCALE, cover: 11, coverLh: 0.98 },
      emphasis: "accent-swash",
      footStyle: "mono",
      titleUppercase: false,
      // Lowercase travels with the rest of the core: this look already
      // runs hook and sub lowercase, so a sentence-case title breaks it.
      titleTransform: "lowercase",
      titleDivider: false,
    },
  },

  // Caption — a subtitle/karaoke look. Deliberately outside the supaslides
  // family: its own typeface and a filled accent emphasis. See
  // docs/superpowers/specs/2026-08-27-caption-maximalist-looks-design.md
  caption: {
    id: "caption",
    name: "Caption",
    pins: {
      surface: "dark",
      bg: "none",
      // Text fades inside a filled panel reads as grey mush; the panel and
      // its copy need to arrive as one object instead.
      motion: "stamp",
    },
    overrides: {
      family: "standalone",
      fontFamily: "var(--font-archivo)",
      hookFontFamily: "var(--font-archivo)",
      hookTransform: "uppercase",
      titleTransform: "uppercase",
      quoteTransform: "uppercase",
      statLabelTransform: "uppercase",
      cqwScale: REFERENCE_SCALE,
      // Set explicitly: these looks skip the derived tonal ladder, so the
      // code paths that read ghost / ghostEm / whisper / faint need values.
      ghost: "#EDEDEF",
      ghostEm: "#FFFFFF",
      whisper: "#9A9AA2",
      faint: "#6E6E77",
      subTransform: "none",
      hookLineHeight: 0.98,
      hookFontWeight: 800,
      // Boxed text needs its own size: the legacy adaptive scale was tuned for
      // unboxed headlines and, once padding is added, fills the canvas.
      hookSizeCqw: 9.5,
      hookMaxWidthPct: 92,
      footStyle: "caption",
      panelStyle: "caption",
      panelBg: "#FFFFFF",
      panelText: "#0B0B0C",
      // The quote uses the outlined variant, which draws with panelBorder and
      // renders as nothing without one. A hairline rule, not the sticker rail.
      panelBorder: "#FFFFFF",
      panelBorderCqw: 0.28,
      panelRadius: 0.3,
      panelPad: [0.3, 0.49, 0.22],
      panelMaxWidthCqw: 80,
      emphasisFill: true,
      italicsFace: "inherit",
      decor: CAPTION_DECOR,
      decorMarker: "REC",
      // Task 2 of the look-parity build: pill badge, boxed subtext, swipe
      // arrow — see specs/look-parity-build.md.
      badgeStyle: "pill",
      subPanel: true,
      subPanelMaxWidthCqw: 70,
      arrowButton: true,
    },
  },

  // Maximalist / Y2K — sticker panels, hard offset shadows, rotation.
  // Also standalone: own typeface, filled emphasis, coloured panels.
  maximalist: {
    id: "maximalist",
    name: "Maximalist",
    pins: {
      surface: "dark",
      bg: "none",
      motion: "stamp",
    },
    overrides: {
      family: "standalone",
      fontFamily: "var(--font-bricolage)",
      hookFontFamily: "var(--font-bricolage)",
      hookTransform: "uppercase",
      titleTransform: "uppercase",
      quoteTransform: "uppercase",
      statLabelTransform: "uppercase",
      cqwScale: REFERENCE_SCALE,
      // Ghost carries the accent here (see the editorial-magazine/atelier
      // comment on this same bug) — the reference's unboxed text
      // (statement/list/foot) is coral, not the off-white the supaslides
      // family uses. ghostEm is the light-coral emphasis.
      ghost: "#FF4D6A",
      ghostEm: "#FF8AA0",
      whisper: "#9A9AA2",
      faint: "#6E6E77",
      hookLineHeight: 1.02,
      hookFontWeight: 800,
      // Smaller than caption: the sticker panel adds a border, a shadow and
      // more padding, so the same size would overflow the frame.
      hookSizeCqw: 8.6,
      hookMaxWidthPct: 88,
      footStyle: "sticker",
      panelStyle: "sticker",
      panelRadius: 0,
      panelShadow: 0.26,
      panelPad: [0.5, 0.62, 0.55],
      panelRotate: 2.5,
      panelMaxWidthCqw: 66,
      emphasisFill: true,
      italicsFace: "inherit",
      decor: MAXIMALIST_DECOR,
      // Real-value furniture pass 2026-08-29: a statement/body slide gets
      // the reference's outlined speech bubble (not left unboxed), list
      // rows get the same bubble treatment plus a filled circular numeral,
      // and every slide gets the head-bar tag row. See
      // specs/look-parity-build.md's history for why this look needed a
      // second pass — it predates the corrected copy-real-values rule.
      bodyPanelStyle: "bubble",
      listRowStyle: "bubble",
      listNumStyle: "maximalist",
      headTabs: true,
    },
  },

  // Editorial Magazine — a contents-page reference look, transcribed with
  // real values pulled from supaslides.app/for/@attune's live stylesheet
  // (Fraunces / Source Serif 4, #FF4D6A / #FF8AA0). Standalone: its own
  // typefaces, structure carried by rules and type rather than a filled
  // panel. See specs/look-parity-build.md, Task 3.
  "editorial-magazine": {
    id: "editorial-magazine",
    name: "Editorial Magazine",
    pins: {
      surface: "dark",
      bg: "none",
    },
    overrides: {
      family: "standalone",
      // Body/masthead face. List items and the masthead row read plain
      // fontFamily; only the hook and slide titles switch to the headline
      // serif below.
      fontFamily: "var(--font-source-serif)",
      hookFontFamily: "var(--font-fraunces)",
      titleFontFamily: "var(--font-fraunces)",
      hookTransform: "none",
      titleTransform: "none",
      quoteTransform: "none",
      statLabelTransform: "uppercase",
      cqwScale: REFERENCE_SCALE,
      bg: "#07050A",
      textColor: "#F0EBF4",
      textSecondary: "#B9AFC2",
      accentColor: "#FF4D6A",
      highlightColor: "#FF8AA0",
      // `ghost` is what headline/title/list text actually renders in under a
      // cqwScale look — it wins over hookColor/titleColor below whenever
      // there's no panel (see SlideHook/SlideTitle). The reference's base
      // text is coral, not the tonal off-white the supaslides family uses,
      // so ghost has to carry the accent here; ghostEm is the lighter coral
      // for emphasis/italics.
      ghost: "#FF4D6A",
      ghostEm: "#FF8AA0",
      whisper: "#B9AFC2",
      faint: "#7A6E80",
      hookColor: "#FF4D6A",
      hookFontWeight: 600,
      hookLineHeight: 0.98,
      hookLetterSpacing: "-0.02em",
      hookSizeCqw: 8.6,
      hookMaxWidthPct: 92,
      titleColor: "#FF4D6A",
      titleFontWeight: 600,
      titleDivider: false,
      footStyle: "mono",
      masthead: true,
      listNumStyle: "editorial",
    },
  },

  // Atelier — cheapest of the three new builds: a typeface swap plus small
  // furniture. Real values pulled from the live reference: Dancing Script
  // (headline) against Hanken Grotesk (everything else), uppercase and
  // wide-tracked. Standalone. See specs/look-parity-build.md, Task 4.
  atelier: {
    id: "atelier",
    name: "Atelier",
    pins: {
      surface: "dark",
      bg: "none",
    },
    overrides: {
      family: "standalone",
      fontFamily: "var(--font-hanken-grotesk)",
      hookFontFamily: "var(--font-dancing-script)",
      titleFontFamily: "var(--font-dancing-script)",
      hookTransform: "none",
      titleTransform: "none",
      quoteTransform: "none",
      statLabelTransform: "uppercase",
      cqwScale: REFERENCE_SCALE,
      bg: "#07050A",
      textColor: "#F0EBF4",
      textSecondary: "#B9AFC2",
      accentColor: "#FF4D6A",
      highlightColor: "#FF8AA0",
      // Same ghost/ghostEm-carries-the-accent reasoning as editorial-magazine
      // above — see the comment there.
      ghost: "#FF4D6A",
      ghostEm: "#FF8AA0",
      whisper: "#B9AFC2",
      faint: "#7A6E80",
      hookColor: "#FF4D6A",
      hookFontWeight: 600,
      hookLineHeight: 1.05,
      hookSizeCqw: 15,
      hookMaxWidthPct: 96,
      // The reference's tiny uppercase, wide-tracked supporting copy — its
      // contrast against the script headline is the whole look.
      subTransform: "uppercase",
      subColor: mixHex("#FF4D6A", "#07050A", 0.55),
      titleColor: "#FF4D6A",
      titleFontWeight: 600,
      titleDivider: false,
      listNumStyle: "atelier",
      listTextTransform: "uppercase",
      listTextLetterSpacing: "0.08em",
      footStyle: "mono",
      footFontFamily: "var(--font-dancing-script)",
      footTransform: "none",
    },
  },

  // Creator Note — imitates a social post rather than a slide. Real values
  // pulled from the live reference: Archivo (headline, already loaded for
  // Caption) over Plus Jakarta Sans (everything else), coral, a coral swash
  // underline under emphasised phrases (the existing "accent-swash" emphasis
  // mode — no new rendering code needed for that part). Most work of the
  // three new looks. See specs/look-parity-build.md, Task 5.
  "creator-note": {
    id: "creator-note",
    name: "Creator Note",
    pins: {
      surface: "dark",
      bg: "finegrid",
    },
    overrides: {
      family: "standalone",
      fontFamily: "var(--font-plus-jakarta)",
      hookFontFamily: "var(--font-archivo)",
      titleFontFamily: "var(--font-archivo)",
      hookTransform: "none",
      titleTransform: "none",
      quoteTransform: "none",
      statLabelTransform: "uppercase",
      cqwScale: REFERENCE_SCALE,
      bg: "#07050A",
      textColor: "#F0EBF4",
      textSecondary: "#B9AFC2",
      accentColor: "#FF4D6A",
      highlightColor: "#FF8AA0",
      ghost: "#FF4D6A",
      ghostEm: "#FF8AA0",
      whisper: "#7A6E80",
      faint: "#7A6E80",
      hookColor: "#FF4D6A",
      hookFontWeight: 800,
      hookLineHeight: 1.02,
      hookSizeCqw: 8.6,
      hookMaxWidthPct: 92,
      // The reference's hand-drawn underline under an emphasised phrase is
      // this existing swash mode, not a new component.
      emphasis: "accent-swash",
      titleColor: "#FF4D6A",
      titleFontWeight: 800,
      titleDivider: false,
      topHairline: true,
      creatorHeader: true,
      arrowButton: true,
    },
  },
};

/**
 * srgb mix of two hex colours — the `color-mix(in srgb, a P%, b)` the reference
 * uses for its tonal ladder. `amount` is a's share, 0..1.
 */
export function mixHex(a: string, b: string, amount: number): string {
  const parse = (h: string) => {
    const v = h.replace("#", "");
    const full = v.length === 3 ? v.split("").map((c) => c + c).join("") : v;
    return [0, 2, 4].map((i) => parseInt(full.slice(i, i + 2), 16));
  };
  const [r1, g1, b1] = parse(a);
  const [r2, g2, b2] = parse(b);
  const ch = (x: number, y: number) =>
    Math.round(x * amount + y * (1 - amount))
      .toString(16)
      .padStart(2, "0");
  return `#${ch(r1, r2)}${ch(g1, g2)}${ch(b1, b2)}`;
}

/** Background type a look pins, if any. */
export function lookBgType(lookId: LookId): BgType | undefined {
  return LOOKS[lookId].pins.bg;
}

/** Motion preset a look pins, if any. */
export function lookMotionId(lookId: LookId): MotionId | undefined {
  return LOOKS[lookId].pins.motion;
}

/**
 * A lighter wash of the accent, used as the ground of a filled panel. Mixes
 * the accent toward white by 45%, which is roughly the reference's
 * #FF4D6A -> #FF8AA0 relationship.
 */
export function accentTint(hex: string): string {
  const h = hex.replace("#", "");
  const n = parseInt(h.length === 3 ? h.split("").map((c) => c + c).join("") : h, 16);
  const mix = (v: number) => Math.round(v + (255 - v) * 0.45);
  const r = mix((n >> 16) & 255);
  const g = mix((n >> 8) & 255);
  const b = mix(n & 255);
  return `rgb(${r},${g},${b})`;
}

export function composePreset(
  font: FontStyle,
  surface: Surface,
  accent: Accent,
  purpose: PurposeId,
  lookId: LookId = "none"
): StylePreset {
  const base: StylePreset = {
    id: `${font.id}-${surface.id}-${accent.id}`,
    name: `${font.name} / ${surface.name} / ${accent.name}`,
    bg: surface.bg,
    bgGradient: surface.bgGradient,
    textColor: surface.textColor,
    textSecondary: surface.textSecondary,
    accentColor: surface.accentColor,
    highlightColor: accent.color,
    fontFamily: font.fontFamily,
    hookFontFamily: font.hookFontFamily,
  };

  const look = LOOKS[lookId];

  // Soft Organic paints the headline in the accent colour itself. Resolved here
  // rather than in the look literal, since it depends on the chosen accent.
  let lookOverrides: Partial<StylePreset> = look.overrides;

  if (lookId === "soft-organic") {
    lookOverrides = { ...look.overrides, hookColor: accent.color, accentColor: accent.color };
  } else if (lookId === "maximalist") {
    // Every other colour in this look is already accent-derived (the panel
    // fill/border, the list/head furniture) — ghost/ghostEm need to follow
    // the same picker so unboxed text (statement/list/foot) doesn't go
    // out of sync with a different accent choice.
    lookOverrides = { ...look.overrides, ghost: accent.color, ghostEm: accentTint(accent.color) };
  } else if (look.overrides.cqwScale && look.overrides.family !== "standalone") {
    // The tonal ladder, and the reason `family` is load-bearing rather than
    // documentation: cqwScale is a SIZING system, but the ladder below is the
    // supaslides family's COLOUR system. A standalone look opts into the
    // former so it holds proportion across formats, while keeping its own
    // colours — caption's white box and maximalist's accent panel would both
    // be destroyed by the ladder.
    //
    // Every text colour in a family look is the surface text mixed back toward
    // the surface background, so the look holds together on any accent and
    // nothing is ever pure white on pure black.
    const bg = look.overrides.bg ?? surface.bg;
    const text = look.overrides.textColor ?? surface.textColor;
    lookOverrides = {
      ...look.overrides,
      ghost: mixHex(text, bg, 0.64),
      ghostEm: mixHex(text, bg, 0.86),
      whisper: mixHex(text, bg, 0.38),
      faint: mixHex(text, bg, 0.26),
      textSecondary: mixHex(text, bg, 0.38),
      accentColor: accent.color,
      highlightColor: accent.color,
    };
  }

  const out: StylePreset =
    purpose === "presentation"
      ? {
          ...base,
          titleFontSize: 72,
          titleFontWeight: 700,
          titleUppercase: false,
          titleDivider: false,
          bodyFontWeight: 400,
          bodyColor: surface.textSecondary,
          bodyLineHeight: 1.45,
          ...lookOverrides,
        }
      : { ...base, ...lookOverrides };

  // Maximalist's panel colours are accent-derived, so they're resolved here
  // (after the look overrides are merged) rather than statically in the look.
  if (out.panelStyle === "sticker") {
    out.panelBg = out.panelBg ?? accentTint(out.highlightColor);
    out.panelBorder = out.panelBorder ?? out.highlightColor;
    out.panelText = out.panelText ?? "#0B0B0C";
  }

  return out;
}

// ---- Format presets (canvas dimensions) ----

export const FORMAT_PRESETS: Record<FormatId, FormatPreset> = {
  "threads-4x5": {
    id: "threads-4x5",
    name: "Threads / Instagram 4:5",
    w: 1080,
    h: 1350,
    platform: "Threads, Instagram",
  },
  "instagram-square": {
    id: "instagram-square",
    name: "Square 1:1",
    w: 1080,
    h: 1080,
    platform: "Instagram, Facebook, LinkedIn",
  },
  "linkedin-square": {
    id: "linkedin-square",
    name: "LinkedIn PDF",
    w: 1080,
    h: 1080,
    platform: "LinkedIn (PDF document)",
  },
  "tiktok-9x16": {
    id: "tiktok-9x16",
    name: "TikTok 9:16",
    w: 1080,
    h: 1920,
    platform: "TikTok, Reels, Shorts",
  },
  "story-9x16": {
    id: "story-9x16",
    name: "Story 9:16",
    w: 1080,
    h: 1920,
    platform: "Instagram Stories, Threads",
  },
  "wide-16x9": {
    id: "wide-16x9",
    name: "Wide 16:9",
    w: 1920,
    h: 1080,
    platform: "Presentations, YouTube, Desktop",
  },
};
