// GENERATED by npm run sync-studio from the threads-carousel fork. Do not edit here.
// @ts-nocheck
// ============================================================
// Shared type definitions for carousel slides and presets.
// Imported by both page.tsx (browser preview) and any future
// server-side renderer (e.g. Satori export script).
// ============================================================

export type SlideType =
  | "hook"
  | "body"
  | "cta"
  | "quote"
  | "stats"
  | "list"
  | "checklist"
  | "process"
  | "comparison"
  | "image"
  | "emoji"
  | "number";

export type BgType =
  | "none"
  | "blobs"
  | "grid"
  | "lines"
  | "noise"
  | "bignumber"
  | "glow"
  | "paper"
  | "bloom"
  | "aurora"
  | "stealthbloom"
  | "sunglow"
  | "organicbloom"
  | "swissrule"
  | "finegrid";

export type FormatId =
  | "threads-4x5"
  | "instagram-square"
  | "linkedin-square"
  | "tiktok-9x16"
  | "story-9x16"
  | "wide-16x9";

// ---- Three independent style axes ----

/** Font / typeface selection */
export type FontId = "minimal" | "editorial" | "clean" | "mono" | "condensed";

/** Surface — bg + text neutrals (no pop color). */
export type SurfaceId =
  | "dark"
  | "white"
  | "light"
  | "paper"
  | "gradient"
  | "pastel"
  | "neon"
  | "ember";

/** Accent — the pop color used for highlighted words. */
export type AccentId =
  | "yellow"
  | "red"
  | "teal"
  | "coral"
  | "orange"
  | "violet"
  | "lime"
  | "blue"
  | "fuchsia"
  | "pink"
  | "amber";

/** Layout purpose — drives typography scale */
export type PurposeId = "carousel" | "presentation";

/**
 * Curated complete looks. A look pins the style axes to a combination that has
 * been checked, and may override typography beyond what the axes can express.
 * "none" leaves the three axes under manual control.
 */
export type LookId =
  | "none"
  | "soft-organic"
  | "aurora"
  | "stealth"
  | "swiss"
  | "vista"
  | "editorial-look"
  | "organic"
  | "caption"
  | "maximalist"
  | "editorial-magazine"
  | "atelier"
  | "creator-note";

/** Motion preset used by the animated export. */
export type MotionId = "editorial" | "kinetic" | "drift" | "stamp";

/**
 * Timeline shape for one slide. All band values are fractions of normalised
 * progress t, so changing the slide duration stretches them proportionally.
 */
export interface MotionPreset {
  id: MotionId;
  name: string;
  /** t at which the last text layer has finished entering. */
  entranceEnd: number;
  /** t offset between consecutive layers. */
  stagger: number;
  /** How long one layer takes to enter, in t. */
  layerDuration: number;
  /** Starting offset in px for the rise. */
  riseFrom: number;
  /** Starting scale for text. 1 disables scaling. */
  scaleFrom: number;
  bgScaleFrom: number;
  bgScaleTo: number;
  /** Background travel in px across the full timeline. 0 disables drift. */
  bgDriftPx: number;
  /**
   * Starting horizontal offset in px, alternating sign by layer index — a
   * panel and its text arrive as one object rather than fading in place.
   * 0 (default) disables horizontal travel entirely.
   */
  travelXFrom?: number;
  /**
   * Multiplies how fast opacity saturates relative to the transform's
   * landing progress, so a filled panel never sits half-see-through on top
   * of its own background. 1 (default) ties opacity directly to the
   * transform's easing, matching the three original presets exactly.
   */
  opacityBoost?: number;
  /**
   * Back-ease overshoot constant for translateX/translateY/scale — the
   * layer lands past its resting position and springs back. 0 (default)
   * falls back to the plain decelerating ease the original presets use.
   */
  overshoot?: number;
}

export interface FontStyle {
  id: FontId;
  name: string;
  fontFamily: string;
  hookFontFamily?: string;
}

export interface Surface {
  id: SurfaceId;
  name: string;
  bg: string;
  bgGradient?: string;
  textColor: string;
  textSecondary: string;
  /** Color used for titles, dividers, badges. For most surfaces equals textColor. */
  accentColor: string;
}

export interface Accent {
  id: AccentId;
  name: string;
  /** Color used for highlighted words. */
  color: string;
}

/**
 * A curated look. `pins` sets the style axes; `overrides` are applied on top of
 * the composed preset for typography a look needs but the axes cannot express.
 */
export interface Look {
  id: LookId;
  name: string;
  /** Axis values this look selects. Omitted axes keep the user's current choice. */
  pins: {
    font?: FontId;
    surface?: SurfaceId;
    bg?: BgType;
    motion?: MotionId;
  };
  /** Applied over the composed preset. */
  overrides: Partial<StylePreset>;
}

/** A decorative glyph pinned to a corner of the frame. */
export interface DecorSticker {
  glyph: string;
  /** Percentages of canvas width/height from the top-left. */
  x: number;
  y: number;
  /** Size in cqw. */
  size: number;
  rotate?: number;
}

export interface ResolvedDecor {
  label?: string;
  stickers: DecorSticker[];
}

/** One entry per slide index; the table repeats once exhausted. */
export type DecorTable = ResolvedDecor[];

export interface SlideDecorOverride {
  label?: string;
  stickers?: DecorSticker[];
  rotate?: number;
}

// ---- Slide data ----

export interface SlideData {
  type: SlideType;
  text?: string;
  /** Lighter paragraph rendered under `text` (hook + body slides). */
  subtext?: string;
  /** Word/phrase inside `subtext` to color with the accent. */
  subHighlight?: string;
  /**
   * Phrases inside `text` rendered in italic serif, keeping the surrounding
   * colour. Independent of `highlight`, and matched case-insensitively.
   * Used by looks that mix roman and italic within a sentence.
   */
  italics?: string[];
  title?: string;
  badge?: string;
  highlight?: string;
  handle?: string;
  // quote
  author?: string;
  role?: string;
  // stats
  stats?: { value: string; label: string }[];
  // list / checklist
  items?: string[];
  // process
  steps?: { title: string; text?: string }[];
  // comparison
  leftLabel?: string;
  leftItems?: string[];
  rightLabel?: string;
  rightItems?: string[];
  // icon points (plus/minus list with SVG icons)
  points?: Array<{ type: "plus" | "minus"; text: string }>;
  // image slide — put file into /public/images/ and reference as "/images/file.png"
  imageSrc?: string;
  imageCaption?: string;
  // emoji slide — single grapheme rendered large
  emoji?: string;
  // number slide — big hero number/string like "17", "5K+", "№1"
  bigNumber?: string;
  // highlight variant — "italic-box" renders highlighted word in Playfair italic on colored box
  highlightStyle?: "default" | "italic-box";
  /** Per-slide panel rotation override, in degrees. Wins over the look's panelRotate. */
  rotate?: number;
  /** Override this slide's furniture. Standalone looks only. */
  stickers?: DecorSticker[];
  /** Override this slide's section label. */
  label?: string;
}

// ---- Internal composed type used by all slide components ----
// Built by composePreset(font, color, purpose) in presets.ts.

export interface StylePreset {
  id: string;
  name: string;
  bg: string;
  bgGradient?: string;
  textColor: string;
  textSecondary: string;
  accentColor: string;
  highlightColor: string;
  fontFamily: string;
  hookFontFamily?: string;
  // Title overrides — defaults: 44px, 800, uppercase, accentColor, divider visible
  titleFontSize?: number;
  titleFontWeight?: number;
  titleUppercase?: boolean;
  /**
   * Case for slide titles. Takes precedence over `titleUppercase`, and
   * mirrors `hookTransform` / `subTransform` so a look can run its whole
   * typographic core in one case.
   */
  titleTransform?: "none" | "lowercase" | "uppercase";
  /**
   * Which rule set a look belongs to. "supaslides" looks share one
   * typographic core (Manrope 800 lowercase, tonal emphasis). "standalone"
   * looks deliberately do not — see the caption/maximalist spec. Absent
   * means unclassified.
   */
  family?: "supaslides" | "standalone";
  /** Boxed treatment applied to headline, stat numeral and quote. */
  panelStyle?: "caption" | "sticker";
  panelBg?: string;
  panelText?: string;
  panelBorder?: string;
  /** Hard offset shadow, in em, e.g. 0.26. Omitted means no shadow. */
  panelShadow?: number;
  /** Panel border width in cqw. Defaults to 1.2. */
  panelBorderCqw?: number;
  /** Max panel width in cqw, so the box hugs its copy instead of the column. */
  panelMaxWidthCqw?: number;
  /** Corner radius in em. 0 for hard corners. */
  panelRadius?: number;
  /** Base rotation in degrees. Sign alternates by slide index. */
  panelRotate?: number;
  /** Padding in em, as [top, x, bottom]. */
  panelPad?: [number, number, number];
  titleDivider?: boolean;
  titleColor?: string;
  // Body text overrides — defaults: 600, textColor, lineHeight 1.2
  bodyFontWeight?: number;
  bodyColor?: string;
  bodyLineHeight?: number;
  /** Body-headline typeface. Defaults to fontFamily. */
  bodyFontFamily?: string;
  // Subtext overrides — the lighter paragraph under the headline.
  // Distinct from body*, which styles the body slide's own headline.
  subFontFamily?: string;
  subFontWeight?: number;
  subColor?: string;
  subLineHeight?: number;
  // Hook overrides — defaults: 800, textColor, lineHeight 1.02, no transform
  hookFontWeight?: number;
  hookColor?: string;
  hookLineHeight?: number;
  hookLetterSpacing?: string;
  hookTransform?: "none" | "lowercase" | "uppercase";
  /** Subtext size clamp override — defaults to 40..56 */
  subTextMaxSize?: number;

  // ---- supaslides-derived looks (Aurora and its siblings) ----
  //
  // These looks do not emphasise with a pop colour. They derive a tonal ladder
  // from the surface — text mixed back toward the background by a percentage —
  // and emphasise by making a phrase *brighter* than its surroundings.
  /** Base headline colour: text mixed 64% over bg. */
  ghost?: string;
  /** Emphasised phrase inside a headline: text mixed 86% over bg. */
  ghostEm?: string;
  /** Supporting copy: text mixed 38% over bg. */
  whisper?: string;
  /** Footer and hairlines: text mixed 26% over bg. */
  faint?: string;
  /**
   * Headline size as a fraction of canvas width, in percent — the reference
   * sizes everything in cqw so a look holds its proportions in any format.
   * 12.5 means 12.5% of canvas width.
   */
  hookSizeCqw?: number;
  /** Headline max width as a percentage of the text column. */
  hookMaxWidthPct?: number;
  /** Supporting-copy size as a fraction of canvas width, in percent. */
  subSizeCqw?: number;
  /** Supporting-copy max width, percent of the text column. */
  subMaxWidthPct?: number;
  /** Supporting-copy case. */
  subTransform?: "none" | "lowercase" | "uppercase";
  /**
   * Case for quote text. Absent keeps the historical behaviour: lowercase
   * under a cqw look, as authored otherwise.
   */
  quoteTransform?: "none" | "lowercase" | "uppercase";
  /**
   * Case for stat labels. Absent keeps the historical behaviour: lowercase
   * under a cqw look, uppercase otherwise.
   */
  statLabelTransform?: "none" | "lowercase" | "uppercase";
  /**
   * How an `italics` phrase is rendered. "serif" is the original italic
   * Playfair cut; "tonal" keeps the face and brightens the phrase instead,
   * which is how the supaslides looks emphasise.
   */
  emphasis?: "serif" | "tonal" | "accent" | "accent-italic" | "accent-swash" | "script";
  /**
   * Type scale in cqw — every size a fraction of canvas width, so a look holds
   * its proportions in any format. Present only on the supaslides-derived
   * looks; its absence keeps the original length-adaptive px sizing.
   */
  cqwScale?: CqwScale;
  /** Footer treatment. "dots" is the original pager; "mono" is @handle / NN. */
  footStyle?: "dots" | "mono" | "caption" | "sticker";
  /**
   * Render the accent dot motif — a breathing circle closing the cover
   * headline, and small inline dots in place of list bullets.
   */
  accentDot?: boolean;
  /**
   * Render an emphasised phrase as a filled accent box rather than the
   * family's tonal lift. Standalone looks only.
   */
  emphasisFill?: boolean;
  /**
   * How an `italics` phrase's typeface is chosen. "serif" (default) applies
   * the original italic Playfair cut, shared by the supaslides family.
   * "inherit" keeps the look's own font family and only applies
   * `fontStyle: italic` — for standalone looks with their own typefaces.
   */
  italicsFace?: "serif" | "inherit";
  /** Deterministic furniture for a standalone look. */
  decor?: DecorTable;
  /** Marker rendered top-right, e.g. "REC". */
  decorMarker?: string;
  /**
   * Badge treatment. Absent keeps the historical bordered-outline/mono-label
   * branch. "tiny-lowercase" is a muted, uppercase-free corner label —
   * Soft Organic's furniture, in place of a pill or bordered badge.
   */
  badgeStyle?: "pill" | "tiny-lowercase";
  /**
   * Box the supporting line in its own panel, smaller than the headline's,
   * left-aligned under it with a small gap — the reference's second white
   * slab. Reuses `panelBg`/`panelText`; size/radius/padding can be
   * overridden with the sub-panel-specific fields below.
   */
  subPanel?: boolean;
  subPanelMaxWidthCqw?: number;
  subPanelRadius?: number;
  subPanelPad?: [number, number, number];
  /** Circular accent-filled swipe-affordance button, bottom right. */
  arrowButton?: boolean;
  /**
   * Slide-title typeface override. Defaults to `fontFamily`. Editorial
   * Magazine's list/stat headings run in its headline serif, not its body
   * serif, so title needs its own face independent of `hookFontFamily`
   * (which only reaches the hook slide).
   */
  titleFontFamily?: string;
  /**
   * Full-width masthead row furniture: issue number left, this slide's
   * `label` centred in italic, folio right, sitting on a full-width rule.
   */
  masthead?: boolean;
  /**
   * Numeral treatment for list items. "editorial" is italic serif + a
   * hairline row divider; "atelier" is a large script numeral, unpadded
   * ("1", not "01"), no divider; "vista" is a circled numeral with a
   * hairline row divider; "dot" is a small filled dot, no divider — like
   * `accentDot` but independent of `cqwScale`.
   */
  listNumStyle?: "editorial" | "atelier" | "vista" | "dot" | "maximalist";
  /** List item text case. Defaults to lowercase under a cqw look, none otherwise. */
  listTextTransform?: "none" | "lowercase" | "uppercase";
  /** List item text tracking. Defaults to -0.02em under a cqw look, -0.01em otherwise. */
  listTextLetterSpacing?: string;
  /**
   * Wrap each list row in a box. "pill" is Soft Organic's soft translucent
   * rounded pill; "bubble" is Maximalist's thick-bordered, alternating-fill
   * rounded row (same border/fill as `bodyPanelStyle: "bubble"`, at row
   * scale).
   */
  listRowStyle?: "pill" | "bubble";
  /**
   * Boxed treatment for a body/statement slide's main line — distinct from
   * `panelStyle` (which boxes the *hook*). "bubble" is Maximalist's
   * outlined speech-bubble: thick border, near-black fill, a leading quote
   * glyph and a small triangular tail, rotated like the hook panel.
   */
  bodyPanelStyle?: "bubble";
  /** Footer typeface override for `footStyle: "mono"`. Defaults to the mono font. */
  footFontFamily?: string;
  /** Footer case override for `footStyle: "mono"`. Defaults to lowercase. */
  footTransform?: "none" | "lowercase" | "uppercase";
  /** Thin accent rule across the very top edge — Creator Note's card frame. */
  topHairline?: boolean;
  /**
   * Social-post header furniture: `@handle` + a verified tick top left,
   * `NN / total` top right; an optional small-caps footer line bottom left
   * from this slide's `label`, when set.
   */
  creatorHeader?: boolean;
  /** Thin accent frame inset from the whole card — Vista's furniture. */
  cardFrame?: boolean;
  /**
   * Small-mono-caps header triad: `headerBrand` · this slide's `label` ·
   * a page number, separated by a bullet — Vista's furniture.
   */
  headerTriad?: boolean;
  /** Fixed left segment of `headerTriad`, e.g. "Est. Vista". */
  headerBrand?: string;
  /** Radial burst of fine rays rising from bottom centre — Vista's furniture. */
  radialRays?: boolean;
  /**
   * Head-bar furniture: a filled, rotated `@handle` tag left, a plain
   * mono kicker word centre (derived from this slide's type), a filled,
   * counter-rotated page-count tag right — Maximalist's furniture.
   */
  headTabs?: boolean;
}

/**
 * Per-role type sizes as a percentage of canvas width, transcribed from the
 * reference. Only `cover` and `coverLh` vary between looks.
 */
export interface CqwScale {
  cover: number;
  coverLh: number;
  /** Body-slide statement line. */
  stmt: number;
  statNum: number;
  statLabel: number;
  statSupport: number;
  listTitle: number;
  listText: number;
  stepLabel: number;
  stepTitle: number;
  stepBody: number;
  cta: number;
  ctaHandle: number;
  sub: number;
  foot: number;
}

export interface FormatPreset {
  id: FormatId;
  name: string;
  w: number;
  h: number;
  platform: string;
}
