import { describe, it, expect } from "vitest";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { FORK_SRC, STUDIO_DIR, transformCss, transformEditor, transformLib } from "../src/studioSync.js";

const editor = `"use client";\nimport { SLIDES, WATERMARK } from "../slides";\nconst hide = process.env.NEXT_PUBLIC_HIDE_MP4 !== "1";\n`;

describe("transformEditor", () => {
  it("points the slides import at the deck module", () => {
    const out = transformEditor(editor);
    expect(out).toContain(`from "../deck";`);
    expect(out).not.toContain(`from "../slides";`);
  });
  it("hard codes the MP4 guard so the button is always hidden in agentco", () => {
    expect(transformEditor(editor)).toContain(`const hide = "1" !== "1";`);
  });
  it("marks the file generated and unchecked", () => {
    const out = transformEditor(editor);
    expect(out.startsWith("// GENERATED by npm run sync-studio")).toBe(true);
    expect(out).toContain("// @ts-nocheck");
  });
  it("refuses a fork that no longer imports ../slides", () => {
    expect(() => transformEditor(editor.replace(`"../slides"`, `"../other"`))).toThrow(/\.\.\/slides/);
  });
  it("refuses a fork without the MP4 guard", () => {
    expect(() => transformEditor(editor.replace("process.env.NEXT_PUBLIC_HIDE_MP4", "x"))).toThrow(/NEXT_PUBLIC_HIDE_MP4/);
  });
});

describe("transformLib", () => {
  it("adds the banner and leaves the code alone", () => {
    expect(transformLib("export const a = 1;\n")).toMatch(/@ts-nocheck\nexport const a = 1;\n$/);
  });
});

describe("transformCss", () => {
  const css = `@import "tailwindcss";\n\nbody { margin: 0; }\n\n/* Toolbar buttons — x */\n.tb-btn { color: red; }\n`;
  it("keeps only the builder's own rules from the toolbar marker on", () => {
    const out = transformCss(css);
    expect(out).toContain(".tb-btn { color: red; }");
    expect(out).not.toContain("tailwindcss");
    expect(out).not.toContain("body {");
  });
  it("refuses CSS without the toolbar marker", () => {
    expect(() => transformCss("body{}")).toThrow(/Toolbar buttons/);
  });
});

describe.skipIf(!existsSync(FORK_SRC))("vendored studio matches the fork", () => {
  it("CarouselApp.tsx", () => {
    const fork = readFileSync(path.join(FORK_SRC, "app/CarouselApp.tsx"), "utf8");
    expect(readFileSync(path.join(STUDIO_DIR, "app/CarouselApp.tsx"), "utf8")).toBe(transformEditor(fork));
  });
  it("lib files", () => {
    for (const f of readdirSync(path.join(FORK_SRC, "lib")).filter((n) => n.endsWith(".ts"))) {
      const fork = readFileSync(path.join(FORK_SRC, "lib", f), "utf8");
      expect(readFileSync(path.join(STUDIO_DIR, "lib", f), "utf8"), f).toBe(transformLib(fork));
    }
  });
  it("studio.css", () => {
    const fork = readFileSync(path.join(FORK_SRC, "app/globals.css"), "utf8");
    expect(readFileSync(path.join(STUDIO_DIR, "studio.css"), "utf8")).toBe(transformCss(fork));
  });
});
