import { homedir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * The carousel editor is authored in Denis's threads-carousel fork and
 * vendored into agentco, because Vercel builds agentco's repo only. These
 * transforms are the whole difference between the two copies, so the drift
 * test can prove the vendored files are exactly the fork, transformed.
 */

export const FORK_SRC = process.env.CAROUSEL_FORK_SRC
  ?? path.join(homedir(), ".claude/skills/threads-carousel/template/src");

export const STUDIO_DIR = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)), "../web/app/carousels/studio",
);

const BANNER =
  "// GENERATED by npm run sync-studio from the threads-carousel fork. Do not edit here.\n" +
  "// @ts-nocheck\n";

const SLIDES_IMPORT = /from "\.\.\/slides";/;
const MP4_GUARD = "process.env.NEXT_PUBLIC_HIDE_MP4";
const CSS_MARKER = "/* Toolbar buttons";

export function transformEditor(src: string): string {
  if (!SLIDES_IMPORT.test(src)) {
    throw new Error('CarouselApp.tsx no longer imports "../slides"; update sync-studio');
  }
  if (!src.includes(MP4_GUARD)) {
    throw new Error("CarouselApp.tsx has no NEXT_PUBLIC_HIDE_MP4 guard; apply the fork change first");
  }
  return BANNER + src.replace(SLIDES_IMPORT, 'from "../deck";').replaceAll(MP4_GUARD, '"1"');
}

export function transformLib(src: string): string {
  return BANNER + src;
}

export function transformCss(src: string): string {
  const at = src.indexOf(CSS_MARKER);
  if (at === -1) throw new Error("globals.css has no /* Toolbar buttons marker; update sync-studio");
  return "/* GENERATED by npm run sync-studio from the threads-carousel fork. Do not edit here. */\n" + src.slice(at);
}
